# Generated by Django 2.2.2 on 2019-07-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/postagem/'),
        ),
    ]
