# Generated by Django 2.2.2 on 2019-07-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotocapa/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotoperfil/'),
        ),
    ]
